# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d5a7f1acbf4b53a409785ff646eee02bfb8574b59ba5fd7054260b2bc659fa98ed4860187328536f7b32d9a1c6b48cece34e160248648d3c5468648fe0f0d9d

test:
  secret_key_base: 46a22c2d486f871157a323ad8dfd7f7c9b3f04bdc5c266396ce06ca3caa4c7c2fd9204fd88b3307b67052716dcc90ed02962d718c916b637cfba5018837477ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
